name: Free Windows RDP Server

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Tailscale
      run: |
        Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi" -OutFile "tailscale-setup.msi"
        Start-Process msiexec.exe -Wait -ArgumentList '/i tailscale-setup.msi /quiet'
        Start-Sleep -Seconds 10

    - name: Connect to Tailscale
      run: |
        & "C:\Program Files\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=github-rdp-server
        Start-Sleep -Seconds 5

    - name: Get Tailscale IP
      run: |
        $ip = & "C:\Program Files\Tailscale\tailscale.exe" ip -4
        Write-Host "=========================================="
        Write-Host "Tailscale IP Address: $ip"
        Write-Host "=========================================="

    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 0
        Write-Host "RDP has been enabled"

    - name: Set Administrator Password
      run: |
        $password = "Admin@2025"
        net user runneradmin $password
        Write-Host "Password set for runneradmin"

    - name: Display Connection Info
      run: |
        $ip = & "C:\Program Files\Tailscale\tailscale.exe" ip -4
        Write-Host ""
        Write-Host "=========================================="
        Write-Host "   RDP CONNECTION INFORMATION"
        Write-Host "=========================================="
        Write-Host "Tailscale IP: $ip"
        Write-Host "Username: runneradmin"
        Write-Host "Password: Admin@2025"
        Write-Host "=========================================="
        Write-Host ""
        Write-Host "To connect:"
        Write-Host "1. Install Tailscale from: https://tailscale.com/download"
        Write-Host "2. Login to Tailscale with your GitHub account"
        Write-Host "3. Open Remote Desktop Connection (mstsc)"
        Write-Host "4. Enter IP: $ip"
        Write-Host "5. Username: runneradmin"
        Write-Host "6. Password: Admin@2025"
        Write-Host "=========================================="

    - name: Keep Server Running
      run: |
        Write-Host ""
        Write-Host "=========================================="
        Write-Host "SERVER IS NOW RUNNING!"
        Write-Host "You can connect anytime using the info above"
        Write-Host "This server will run for up to 6 hours"
        Write-Host "=========================================="
        Write-Host ""
        
        $counter = 0
        while ($true) {
          Start-Sleep -Seconds 300
          $counter += 5
          Write-Host "Server running for $counter minutes... $(Get-Date)"
          
          # Display connection info every 30 minutes
          if ($counter % 30 -eq 0) {
            $ip = & "C:\Program Files\Tailscale\tailscale.exe" ip -4
            Write-Host ""
            Write-Host "=========================================="
            Write-Host "REMINDER: Connection Info"
            Write-Host "IP: $ip | User: runneradmin | Pass: Admin@2025"
            Write-Host "=========================================="
            Write-Host ""
          }
        }

